Revert 8125 "Modify some tests to never use DTX disable mode"
Broke compile on the Chromium FYI bots:
http://build.chromium.org/p/chromium.webrtc.fyi/builders/Win%20Builder/builds/3483
http://build.chromium.org/p/chromium.webrtc.fyi/builders/Mac/builds/16028
http://build.chromium.org/p/chromium.webrtc.fyi/builders/Linux/builds/14293

Error:
In file included from ../../third_party/webrtc/voice_engine/channel.cc:13:
In file included from ../../third_party/webrtc/base/checks.h:22:
In file included from ../../third_party/webrtc/overrides/webrtc/base/logging.h:35:
../../base/logging.h:367:9:error: 'LOG' macro redefined [-Werror,-Wmacro-redefined]
#define LOG(severity) LAZY_STREAM(LOG_STREAM(severity), LOG_IS_ON(severity))
        ^
../../third_party/webrtc/system_wrappers/interface/logging.h:123:9: note: previous definition is here
#define LOG(sev) \
        ^
In file included from ../../third_party/webrtc/voice_engine/channel.cc:13:
In file included from ../../third_party/webrtc/base/checks.h:22:
../../third_party/webrtc/overrides/webrtc/base/logging.h:189:9:error: 'LOG_V' macro redefined [-Werror,-Wmacro-redefined]
#define LOG_V(sev) DIAGNOSTIC_LOG(sev, NONE, 0)
        ^
../../third_party/webrtc/system_wrappers/interface/logging.h:129:9: note: previous definition is here
#define LOG_V(sev) \
        ^
2 errors generated.

> Modify some tests to never use DTX disable mode
> 
> DTX disable mode will be removed as a part of the ACM redesign work.
> 
> COAUTHOR:kwiberg@webrtc.org
> 
> R=henrika@webrtc.org
> 
> Review URL: https://webrtc-codereview.appspot.com/34769004

TBR=henrik.lundin@webrtc.org

Review URL: https://webrtc-codereview.appspot.com/35859004

Cr-Mirrored-From: https://chromium.googlesource.com/external/webrtc
Cr-Mirrored-Commit: ff108fe5084e8326e7c38be728557758bd58b1e7