Fix log build error for Chromium builds.
This only happens when building in Chromium. Can't roll due to this.

../../third_party/webrtc/modules/desktop_capture/mouse_cursor_monitor_x11.cc: In function 'Window {anonymous}::GetTopLevelWindow(Display*, Window)':
../../third_party/webrtc/modules/desktop_capture/mouse_cursor_monitor_x11.cc:39:7: error: 'LS_INFO' was not declared in this scope
../../third_party/webrtc/modules/desktop_capture/mouse_cursor_monitor_x11.cc:39:7: note: suggested alternative:
../../third_party/webrtc/system_wrappers/interface/logging.h:71:29: note:   'webrtc::LS_INFO'

See for example http://build.chromium.org/p/chromium.webrtc.fyi/builders/Linux%20%5Blatest%20WebRTC%2Blibjingle%5D/builds/3039/steps/compile/logs/stdio

R=henrika@webrtc.org

Review URL: https://webrtc-codereview.appspot.com/3619004

Cr-Mirrored-From: https://chromium.googlesource.com/external/webrtc
Cr-Mirrored-Commit: bff96201166bb8d825618cea077ff1b6e2d352b1